<!DOCTYPE html>

<html>
<head>
	<title>BIBLIOGRAPHIE</title>
	<link rel="stylesheet" type="text/css" href="exemple.css">
</head>
<body>
	<nav class="ha">
		<TABLE>
			<tr>
				<th><img src="aaa.jpg" width="80px" height="80px"></th>
				<th>GRANDIOSE WITH GOD</th>
			</tr>
		</TABLE>
		<ul>
			<center>
			<li><a href="page2.html">Accuiel</a></li>
			<li><a href="site.html">consulter</a></li>
			<li><a href="contact.html">contact</a></li>
			</center>
		</ul>
	</nav>
	<div class="bas">
		<center>
			<h3>Pour tout renseignement et accompagnement veiller nous contacter a ces differentes adresses:</h3>
		<table>
			<tr>
				
				<th><h3>telephone: +243977364661</h3></th>
				<th><h3>gmail: milcakeren7@gmail.com</h3></th>
				<th><h3>facebook : milca MITONGA</h3></th>
			</tr>
		</table>
		</center>
	</div>
	<div>
		
	</div>
</body>
</html>
